title: eosyn
description: >- # this means to ignore newlines until "baseurl:"
  eosyn's personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eosyn-z.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: gen3sys@proton.me
discord_username: eosyn
twitter_username: eosyn_
github_username: eosyn-z
timezone: EST

# remote_theme: "jekyll/minima@1e8a445"
# set to null in order to use the local glass theme.
theme: null

collections:
  sitepages:
    output: true
  desktop:
    output: true
  games:
    output: true
  artpages:
    output: true
  projects:
    output: true
  portfolio:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:name/
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:title/
  - scope:
      path: "_sitepages"
    values:
      permalink: /:name/
  - scope:
      path: "_games"
    values:
      permalink: /:name/
  - scope:
      path: "_artpages"
    values:
      permalink: /:name/
  - scope:
      path: "_projects"
    values:
      permalink: /:name/
  - scope:
      path: "_portfolio"
    values:
      permalink: /portfolio/:title/

# Jekyll-seo-tag settings
# ... existing code ...
