title: eosyn.net
url: https://eosyn.net
email: gen3sys@proton.me
discord_username: eosyn
twitter_username: _eosyn
github_username: eosyn-z
timezone: EST

# remote_theme: "jekyll/minima@1e8a445"
# set to null in order to use the local glass theme.
theme: null
