title: eosyn
description: >- # this means to ignore newlines until "baseurl:"
  eosyn's personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eosyn-z.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: gen3sys@proton.me
discord_username: eosyn
twitter_username: eosyn_
github_username: eosyn-z
timezone: EST

# remote_theme: "jekyll/minima@1e8a445"
# set to null in order to use the local glass theme.
theme: null

permalink: /:name/

collections:
  sitepages:
    output: true
  desktop:
    output: true
  games:
    output: true
  artpages:
    output: true
  projects:
    output: true
  portfolio:
    output: true
    permalink: /portfolio/:title/

# Jekyll-seo-tag settings
# ... existing code ...
