title: eosyn
description: >-
  eosyn's personal website
baseurl: ""
url: "https://eosyn-z.github.io"
email: gen3sys@proton.me
discord_username: eosyn
twitter_username: eosyn_
github_username: eosyn-z
timezone: EST

theme: null

permalink: /:name/

collections:
  artpages:
    output: true
    permalink: /portfolio/art/:title/
  projects:
    output: true
    permalink: /portfolio/projects/:title/
  desktop:
    output: true
  games:
    output: true
    permalink: /games/:title/
  sitepages:
    output: true
    # mark this collection as the source for nav pages
    metadata:
      nav: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
